### ISSUE TITLE
Rsync task does not recognize the server password

### ISSUE THREAD

**Issue by Baachi** [deployphp/recipes#32] opened 2015-08-25 07:34 UTC
Hey guys,

it seems the rsync task does not recognize the server password. The script ask me everytime for the server password.

Maybe this is a bug?

**Comment by johnny-bit** [comment] 2015-08-25 08:02
Is not a bug is a known feature of rsync. cannot pass password via params
to rsync, so either you'll have to setup passwordless auth (it's easy!),
put up wit passwords everytime (it's bothersome) or me/you/somebody will
come up with expect script for that and PRs it + makes sure it works in all
configs/locales which is a bitch to make.

So... yeah. I don't like having to put passwords either, but I have leisure
of being able to set up passwordless auth, while expect scripts are not my
favourite way of dealing with forced inputs.

2015-08-25 9:34 GMT+02:00 Markus Bachmann <notifications@github.com>:

> Hey guys,
>
> it seems the rsync task does not recognize the server password. The script
> ask me everytime for the server password.
>
> Maybe this is a bug?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deployphp/recipes/issues/32>.
>



-- 
Pozdrawiam,
Hubert Kowalski

**Comment by gordalina** [comment] 2015-10-22 18:55
closing this. please reopen if you feel that you should.

**Closed by gordalina** 2015-10-22 18:55 UTC

**Comment by hirnschmalz** [comment] 2016-07-21 06:29
If someone have the same problem: working with keychains may solve your problems ;) At least on Linux (http://www.funtoo.org/Keychain) / macOS
